update celery docs with solo pool
czue/pegasus-docs pull request #91
Opened 2024-08-12 14:38 UTC by snopoke

2024-08-12 15:02 UTC, czue requested changes

2024-08-12 15:02 UTC, czue commented on celery.md
> +tasks).
For now, can you add links to these in the celery docs and/or preserve the guidance on how to run with `gevent`?

2024-08-13 07:15 UTC, snopoke commented on celery.md
> +tasks).
updated

2024-08-13 07:20 UTC, merged

2024-08-13 07:20 UTC, czue commented on celery.md
> +tasks).
thanks